### PR TITLE
Note that it's an error to play with continuations and array-assign!

### PR DESCRIPTION
**Pull request by gambiteer**
srfi-231.scm:

1.  Add comment that it is an error to invoke the continuation of each call to the destination's setter or the source's getter more than once.

srfi-231.html:

1.  Regenerate from srfi-231.scm.

### CODE REVIEW

**Comment by gambiteer** [comment]
Is this the kind of thing you meant?  Brad

**Comment by arthurgleckler** [comment]
On Sun, Feb 12, 2023 at 2:08 PM Bradley Lucier ***@***.***>
wrote:

> Is this the kind of thing you meant? Brad
>
> Post-finalization notes go in the Status section.  If you send me the
wording, I can add it.  It would be good to send it to the list first,
however.  There has been some concern about making semantic changes after
finalization, even in PFNs.  I'd like to get some feedback.

**Comment by gambiteer** [comment]
> On Feb 13, 2023, at 11:30 PM, Arthur A. Gleckler ***@***.***> wrote:
> 
> > Post-finalization notes go in the Status section. If you send me the
> wording, I can add it. It would be good to send it to the list first,
> however. There has been some concern about making semantic changes after
> finalization, even in PFNs. I'd like to get some feedback.

OK, I’ll send the proposed change to the mail list again (I’d sent this exact wording to the mail list before).

I see it as an oversight; array-assign! is the only non-call/cc-safe procedure that uses the setter of an argument, all the others use only getters of arguments.  Some notice of this should have been made.

If you see it as having the same meaning as a post-finalization note as being added to the “Notes” section, as I did here, then I’m OK with it.

Brad

**Comment by arthurgleckler** [comment]
On Mon, Feb 13, 2023 at 8:36 PM Bradley Lucier ***@***.***>
wrote:


> OK, I’ll send the proposed change to the mail list again (I’d sent this
> exact wording to the mail list before).
>

Never mind.  I had lost track of the fact that you had done that.


> I see it as an oversight; array-assign! is the only non-call/cc-safe
> procedure that uses the setter of an argument, all the others use only
> getters of arguments. Some notice of this should have been made.
>

That's a legitimate reason for to mark it as an erratum.  I'll do that.

**Pull request merged**
