### PR TITLE
Make explicit assumptions about procedure arguemnts

### PR DESCRIPTION
**Pull request by gambiteer**
generic-arrays.scm:

1.  Ensure that the elements of array in (array->list array) are evaluated in lexicographical order, as in the spec.

test-arrays.scm:

1.  Test that elements of array in (array->list array) are evaluated in lexicographical order.

srfi-231.scm:

1.  Announce Draft 14.

2.  Make explicit the assumptions of the arguments to many procedures.

srfi-231.html:

1.  Regenerate from srfi-231.scm.

### CODE REVIEW

**Comment by gambiteer** [comment]
If you have no problem with these changes, I don't think there needs to be another announcement on the mail list.

**Comment by arthurgleckler** [comment]
On Tue, Jul 26, 2022 at 12:42 PM Bradley Lucier ***@***.***>
wrote:

> If you have no problem with these changes, I don't think there needs to be
> another announcement on the mail list.
>
> Sounds good.  I've merged them, applied one tiny copy edit, and pushed to
the site.

**Comment by gambiteer** [comment]
On 7/26/22 3:49 PM, Arthur A. Gleckler wrote:
> ---- *External Email*: Use caution with attachments, links, or sharing 
> data ----
> 
> 
> On Tue, Jul 26, 2022 at 12:42 PM Bradley Lucier ***@***.***>
> wrote:
> 
>  > If you have no problem with these changes, I don't think there needs 
> to be
>  > another announcement on the mail list.
>  >
>  > Sounds good. I've merged them, applied one tiny copy edit, and pushed to
> the site.

It looks like you wanted to put the "that" before the 
"<code><var>i</var></code>".

**Comment by arthurgleckler** [comment]
On Tue, Jul 26, 2022 at 12:53 PM Bradley Lucier ***@***.***>
wrote:


> It looks like you wanted to put the "that" before the
> "<code><var>i</var></code>".
>
> Sorry about that.  That's what I get for trying to move too quickly.
Fixed.

**Pull request merged**
